// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ProyectoTopicos.Migrations
{
    [DbContext(typeof(ProyectoTopicosContext))]
    [Migration("20260607045143_add_estudios_independientes")]
    partial class add_estudios_independientes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ProyectoTopicos.Models.Alumno", b =>
                {
                    b.Property<int>("Matricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Creditos")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Promedio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Puntos")
                        .HasColumnType("TEXT");

                    b.HasKey("Matricula");

                    b.ToTable("Tabla_Alumnos", (string)null);
                });

            modelBuilder.Entity("ProyectoTopicos.Models.EstudiosIndependientes", b =>
                {
                    b.Property<int>("Clave_Estudio_Independiente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Creditos_Estudio_Independiente")
                        .HasColumnType("REAL");

                    b.Property<int>("Matricula")
                        .HasColumnType("INTEGER");

                    b.Property<double>("No")
                        .HasColumnType("REAL");

                    b.Property<int>("No_Empleado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("No_Programa_Educativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre_Alumno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre_Estudio_Independiente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre_Profesor_Tutor_Investigar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Plan_de_Estudios")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Programa_Educativo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Clave_Estudio_Independiente");

                    b.ToTable("Estudios_Independiente", (string)null);
                });

            modelBuilder.Entity("ProyectoTopicos.Models.Maestro", b =>
                {
                    b.Property<string>("Numero_Empleado")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Numero_Empleado");

                    b.ToTable("Tabla_Maestros", (string)null);
                });

            modelBuilder.Entity("ProyectoTopicos.Models.Materia", b =>
                {
                    b.Property<int>("ClaveUA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Creditos")
                        .HasColumnType("REAL");

                    b.Property<int>("NoPE")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombrePE")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUA")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanDeEstudios")
                        .HasColumnType("TEXT");

                    b.HasKey("ClaveUA");

                    b.ToTable("Tabla_Materias", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
