// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ProyectoTopicos.Migrations
{
    [DbContext(typeof(ProyectoTopicosContext))]
    [Migration("20260608061507_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("ProyectoTopicos.Models.Alumno", b =>
                {
                    b.Property<int>("Matricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Creditos")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Promedio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Puntos")
                        .HasColumnType("TEXT");

                    b.HasKey("Matricula");

                    b.ToTable("Tabla_Alumnos", (string)null);
                });

            modelBuilder.Entity("ProyectoTopicos.Models.Ayudantias_Investigacion", b =>
                {
                    b.Property<int>("Clave_Ayudantias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Creditos_de_Ayudantia")
                        .HasColumnType("REAL");

                    b.Property<int>("Matricula")
                        .HasColumnType("INTEGER");

                    b.Property<int>("No_Programa_Educativo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("No_de_Empleado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre_Alumno")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre_Empleado")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre_de_Ayudantia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plan_Estudios")
                        .HasColumnType("TEXT");

                    b.Property<string>("Programa_Educativo")
                        .HasColumnType("TEXT");

                    b.HasKey("Clave_Ayudantias");

                    b.ToTable("Ayudantias", (string)null);
                });

            modelBuilder.Entity("ProyectoTopicos.Models.Ayudantias_Laboratorio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Matricula")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre_alumno")
                        .HasColumnType("TEXT");

                    b.Property<string>("clave_ayudantia")
                        .HasColumnType("TEXT");

                    b.Property<int?>("creditos_ayudantia")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("no_programa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nombre_ayudantia_lab")
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre_empleado")
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre_profesor")
                        .HasColumnType("TEXT");

                    b.Property<string>("plan_de_estudios")
                        .HasColumnType("TEXT");

                    b.Property<string>("programa_educativo")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Ayudantias_Laboratorios", (string)null);
                });

            modelBuilder.Entity("ProyectoTopicos.Models.Maestro", b =>
                {
                    b.Property<string>("Numero_Empleado")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Numero_Empleado");

                    b.ToTable("Tabla_Maestros", (string)null);
                });

            modelBuilder.Entity("ProyectoTopicos.Models.Materia", b =>
                {
                    b.Property<int>("ClaveUA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Creditos")
                        .HasColumnType("REAL");

                    b.Property<int>("NoPE")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombrePE")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUA")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanDeEstudios")
                        .HasColumnType("TEXT");

                    b.HasKey("ClaveUA");

                    b.ToTable("Tabla_Materias", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
