// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ProyectoTopicos.Migrations
{
    [DbContext(typeof(ProyectoTopicosContext))]
    partial class ProyectoTopicosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ProyectoTopicos.Models.Alumno", b =>
                {
                    b.Property<int>("Matricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Creditos")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Promedio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Puntos")
                        .HasColumnType("TEXT");

                    b.HasKey("Matricula");

                    b.ToTable("Alumno");
                });
#pragma warning restore 612, 618
        }
    }
}
